apiVersion: 1

datasources:
  - name: UrbanFlow Postgres
    uid: urbanflow-postgres
    type: postgres
    access: proxy
    isDefault: true
    editable: true

    # Usa as vari√°veis de ambiente definidas no .env / container
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}

    jsonData:
      database: ${DB_NAME}
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
